Delete http://localhost:8080/api/user/notes/6290387e612a1a3dd37f9fc9
Content-Type: application/json

{
    "userName": "111",
    "password": "111",
    "event":[{
        "noteForEvent":{
            "noteText":"test note"
        }
    }]
}